# Generated by Django 6.0.5 on 2026-05-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickupBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('scrap_type', models.CharField(choices=[('metal', 'Metal / Iron'), ('paper', 'Paper / Cardboard'), ('electronics', 'Electronics (E-waste)'), ('plastic', 'Plastic'), ('other', 'Other')], max_length=20)),
                ('pickup_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('done', 'Done')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('scrap_type', models.CharField(choices=[('metal', 'Metal / Iron'), ('paper', 'Paper / Cardboard'), ('electronics', 'Electronics (E-waste)'), ('plastic', 'Plastic'), ('other', 'Other')], max_length=20)),
                ('weight_kg', models.FloatField()),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('scrap_type', models.CharField(choices=[('metal', 'Metal / Iron'), ('paper', 'Paper / Cardboard'), ('electronics', 'Electronics (E-waste)'), ('plastic', 'Plastic'), ('other', 'Other')], max_length=20)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(default='PKR/kg', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapItems',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
