# Generated by Django 6.0.5 on 2026-05-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactmessage_pickupbooking_quoterequest_scrapprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupbooking',
            name='scrap_type',
            field=models.CharField(choices=[('metal', 'Metal / Iron'), ('paper', 'Paper / Cardboard'), ('electronics', 'Electronics (E-waste)'), ('plastic', 'Plastic'), ('battery', 'Battery'), ('silver', 'Silver'), ('brass', 'Brass'), ('copper', 'Copper'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='scrap_type',
            field=models.CharField(choices=[('metal', 'Metal / Iron'), ('paper', 'Paper / Cardboard'), ('electronics', 'Electronics (E-waste)'), ('plastic', 'Plastic'), ('battery', 'Battery'), ('silver', 'Silver'), ('brass', 'Brass'), ('copper', 'Copper'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='scrapprice',
            name='scrap_type',
            field=models.CharField(choices=[('metal', 'Metal / Iron'), ('paper', 'Paper / Cardboard'), ('electronics', 'Electronics (E-waste)'), ('plastic', 'Plastic'), ('battery', 'Battery'), ('silver', 'Silver'), ('brass', 'Brass'), ('copper', 'Copper'), ('other', 'Other')], max_length=20),
        ),
    ]
