# Generated by Django 6.0.5 on 2026-05-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
